import './style.css';
import {createState,loadState,saveState,formatTime,advance,daylight,SAVE_KEY} from './simulation.js';
import {createAudio} from './audio.js';
import {createRoom} from './room.js';
import {createSocial} from './social.js';
import {createDesktop} from './desktop.js';
import {createOperator} from './operator.js';
import {createGameInput} from './input.js';
import {createTouchControls} from './touch.js';

const app=document.querySelector('#app');
app.innerHTML=`<div id="world"></div><div class="world-grain"></div><div class="world-vignette"></div>
<main id="menu" class="main-menu"><header class="menu-top"><span class="brand-mark">a<span>_</span></span><span>A NIGHT IN THE LIFE</span><span class="build-tag">VOL. 01 / BROWSER EDITION</span></header>
<div class="menu-copy"><div class="eyebrow"><span class="status-dot"></span> STILL ONLINE</div><h1>ANTI<span>CHAT</span><br>LOGGER<span class="title-small">SIMULATOR</span></h1><p class="menu-subtitle">One room. A few friends.<br>Nowhere you need to be.</p><nav id="main-actions"><button id="continue" class="menu-primary">Continue <span>↗</span></button><button id="new-game">New game <span>01</span></button><button id="menu-settings">Settings <span>02</span></button><button id="credits">Credits <span>03</span></button><button id="quit">Quit <span>04</span></button></nav></div>
<div class="scene-caption"><span class="tiny-label">STEVEN’S ROOM</span><span id="menu-clock">09:18 PM</span><span class="caption-weather">rain against the window</span></div><footer class="menu-footer"><span>HEADPHONES RECOMMENDED</span><span>WASD + MOUSE <i>·</i> TAKE YOUR TIME</span><span>© 2026 ANTICHATLOGGER SIMULATOR</span></footer></main>
<div id="room-hud" hidden><div class="location-tag"><i></i> STEVEN’S ROOM</div><div id="crosshair">·</div><div id="interaction"></div><div id="room-help"><span><kbd>W A S D</kbd> move</span><span><kbd>E</kbd> interact</span><span><kbd>F</kbd> pick up</span><span><kbd>Tab</kbd> phone</span><span><kbd>Esc</kbd> pause</span></div><button id="capture-mouse">Click to look around <span>WASD to move · E to interact</span></button></div>
<div id="bed-hud" hidden><span>Just for a minute.</span><button id="rise">E · Get up</button><button id="bed-phone">Tab · Phone</button><button id="sleep">Sleep until morning</button></div>
<div id="desktop" hidden></div><div id="operator" hidden></div><div id="phone" hidden></div><div id="modal" hidden></div><div id="toast-region" aria-live="polite"></div><div id="subtitle" aria-live="polite" hidden></div><div id="save-indicator" hidden>saved</div>`;
const $=id=>document.getElementById(id);let state=loadState(localStorage),mode='menu',previousMode='room',paused=false,phoneOpen=false,room,desktop,operator,social,touchControls,elapsed=0,lastSave=0,lastBird=0;
const input=createGameInput();
const events=new EventTarget();
function toast(text){const el=document.createElement('div');el.className='toast';el.textContent=text;$('toast-region').append(el);setTimeout(()=>el.remove(),5000);}
function save(){try{room?.savePosition();saveState(state,localStorage);$('save-indicator').hidden=false;setTimeout(()=>$('save-indicator').hidden=true,1200);}catch{toast('Save storage is full. Export your save from the pause menu.');}}
const audio=createAudio(state,events);
const ctx={state,events,audio,input,save,toast,formatTime:()=>formatTime(state.totalMinutes),prompt:text=>{$('interaction').textContent=input.touchEnabled?text.replace('F · Drop   /   Click · Use','Pick / drop · Use').replace(/^E · /,'').replace(/^F · /,'') : text;},enterPC,leavePC,lieDown,togglePhone,openApp,startOperator,resumeOperator,exitOperator:()=>openApp('operator'),isOperatorRunning:()=>operator?.isRunning(),isOperatorParty:()=>operator?.isRunning()&&operator?.getState()?.party,importSave(data){if(data.version!==1||!data.room||!data.needs||!Number.isFinite(data.totalMinutes))throw Error('Invalid save');localStorage.setItem(SAVE_KEY,JSON.stringify(data));state.savedAt=null;location.reload();}};
function setMode(next){input.reset();mode=next;document.body.dataset.mode=mode;$('menu').hidden=mode!=='menu';$('room-hud').hidden=mode!=='room';$('bed-hud').hidden=mode!=='bed';room.setMode(mode==='operator'?'pc':mode);if(mode!=='room')document.exitPointerLock?.();if(mode!=='pc')desktop.hide();if(mode!=='operator')operator.hide();audio.setEnabled(!paused);touchControls?.update();}
function enterPC(){if(paused)return;room.savePosition();setMode('pc');desktop.show();audio.click();save();}
function leavePC(){setMode('room');audio.click();save();room.lock();}
function lieDown(){room.savePosition();setMode('bed');audio.door();save();}
function openApp(name){if(mode==='menu')return;room.savePosition();setMode('pc');desktop.show();desktop.open(name);}
function startOperator(options){if(state.events.outage){toast('No connection. Restart the router on the dresser.');return;}setMode('operator');operator.start(options);audio.init();}
function resumeOperator(){if(operator?.isRunning()){setMode('operator');operator.show();audio.init();}}
function begin(reset=false){audio.init();if(reset){const fresh=createState();Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,fresh);localStorage.removeItem(SAVE_KEY);sessionStorage.setItem('anti-start-new','1');location.reload();return;}setMode('room');save();room.lock();}
function modal(title,body){input.reset();document.exitPointerLock?.();const el=$('modal');el.hidden=false;el.innerHTML=`<div class="modal-panel"><div class="eyebrow">ANTICHATLOGGER SIMULATOR</div><h2>${title}</h2>${body}</div>`;touchControls?.update();}
function closeModal(){paused=false;audio.setEnabled(true);$('modal').hidden=true;}
function pause(){if(paused){closeModal();return;}paused=true;audio.setEnabled(false);document.exitPointerLock?.();modal('Take a minute.',`<div class="pause-time">${ctx.formatTime()} <span>day ${state.day}</span></div><div class="pause-actions"><button data-action="resume" class="solid-btn">Resume</button><button data-action="save">Save game</button><button data-action="export">Export save</button><button data-action="import">Import save</button><button data-action="settings">Settings</button><button data-action="controls">Controls</button><button data-action="main">Save & main menu</button></div><p class="muted">Time is paused. Your friends can wait.</p>`);$('modal').querySelectorAll('[data-action]').forEach(btn=>btn.onclick=()=>{switch(btn.dataset.action){case'resume':closeModal();break;case'save':save();toast('Night saved.');break;case'export':exportSave();break;case'import':importSave();break;case'settings':settings();break;case'controls':controls();break;case'main':save();closeModal();setMode('menu');$('continue').disabled=false;break;}});}
function controls(){if(input.touchEnabled){modal('Make yourself at home.',`<div class="controls-grid"><b>Left stick</b><span>Move</span><b>Drag on the right</b><span>Look around</span><b>Interact / Pick / Use</b><span>Use the room and its objects</span><b>Run / Crouch</b><span>Tap to toggle</span><b>Phone / Pause</b><span>Use the buttons at the top</span><b>Fire / Aim / Extract</b><span>Hold in Operator. Drag Fire to look while shooting.</span><b>Discord / Return to match</b><span>Switch apps without leaving your match</span></div><p class="muted">Works in portrait and landscape. Use Start on the desktop and Conversations in Discord to find everything.</p><button class="solid-btn" id="controls-close">Got it</button>`);$('controls-close').onclick=closeModal;return;}modal('Make yourself at home.',`<div class="controls-grid"><b>WASD / Mouse</b><span>Move / look</span><b>E</b><span>Interact / get out of bed</span><b>F / Left click</b><span>Pick up or drop / use held object</span><b>Shift / C</b><span>Sprint / crouch</span><b>Tab</b><span>Phone (scoreboard inside Operator)</span><b>F2 / Alt + Q</b><span>Switch Operator ↔ Discord</span><b>R / Enter</b><span>Reload / Operator text chat</span><b>Escape</b><span>Release mouse / pause</span></div><p class="muted">The browser reserves Alt-Tab for switching real applications. F2 switches your in-game apps. Click the room or match to capture the mouse.</p><button class="solid-btn" id="controls-close">Got it</button>`);$('controls-close').onclick=closeModal;}
function settings(){modal('Settings',`<div class="settings-list"><label>Master volume <input id="s-volume" type="range" min="0" max="1" step=".05" value="${state.settings.volume}"></label><label>Mouse sensitivity <input id="s-sens" type="range" min=".25" max="2.5" step=".05" value="${state.settings.sensitivity}"></label><label>World pixels <select id="s-pixels"><option value="1">Fine</option><option value="2">PSX — balanced</option><option value="3">Chunky</option></select></label><label>Time passing <select id="s-time"><option value="0.0167">Real time</option><option value="0.15">Slow night · 9×</option><option value="0.3">A long night · 18×</option><option value="1">Quick night · 60×</option></select></label><label>Touch controls <select id="s-touch"><option value="auto">Auto</option><option value="on">On</option><option value="off">Off</option></select></label><label>Voice subtitles <input id="s-subs" type="checkbox" ${state.settings.subtitles?'checked':''}></label></div><p class="muted">Only the physical world is pixelated. Computer text stays sharp.</p><button class="solid-btn" id="settings-close">Done</button>`);$('s-touch').value=state.settings.touchControls||'auto';$('s-touch').onchange=e=>{state.settings.touchControls=e.target.value;touchControls.update();};$('s-pixels').value=state.settings.pixelScale;$('s-time').value=state.settings.timeScale;$('s-volume').oninput=e=>state.settings.volume=+e.target.value;$('s-sens').oninput=e=>state.settings.sensitivity=+e.target.value;$('s-pixels').onchange=e=>{state.settings.pixelScale=+e.target.value;room.resize();};$('s-time').onchange=e=>state.settings.timeScale=+e.target.value;$('s-subs').onchange=e=>state.settings.subtitles=e.target.checked;$('settings-close').onclick=()=>{save();closeModal();};}
function exportSave(){save();const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='anti-night-save.json';a.click();URL.revokeObjectURL(url);}
function importSave(){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const data=JSON.parse(await input.files[0].text());if(data.version!==1||!data.room||!data.needs||!Number.isFinite(data.totalMinutes))throw Error();localStorage.setItem(SAVE_KEY,JSON.stringify(data));state.savedAt=null;location.reload();}catch{toast('That file is not a valid save.');}};input.click();}
function renderPhone(page='home'){
  const el=$('phone');el.dataset.page=page;el.innerHTML=`<div class="phone-shell"><div class="phone-notch"></div><div class="phone-top"><span>${ctx.formatTime()}</span><span>▂▄▆ · 74%</span></div><div class="phone-body"></div><button class="phone-home" aria-label="Phone home"></button><button class="phone-close" aria-label="Close phone">×</button></div>`;const b=el.querySelector('.phone-body');el.querySelector('.phone-close').onclick=()=>togglePhone(false);el.querySelector('.phone-home').onclick=()=>renderPhone();
  if(page==='home'){b.innerHTML=`<p class="phone-date">Sunday, September ${20+(state.day-1)%10}</p><h2 class="phone-clock">${ctx.formatTime().replace(/ [AP]M/,'')}</h2><p class="phone-weather">${state.room.rain?'Light rain':'Overcast'} · 14°</p><div class="phone-apps">${[['messages','◌','Messages'],['discord','☷','Discord'],['food','↗','Delivery'],['bank','▤','Banking'],['music','♫','Music'],['camera','◎','Camera'],['notes','▧','Notes'],['needs','♡','You']].map(([id,icon,label])=>`<button data-phone="${id}"><span>${icon}</span>${label}</button>`).join('')}</div><div class="phone-notice">Discord <small>${social.getUnread()} unread in the gc</small></div>`;b.querySelectorAll('[data-phone]').forEach(btn=>btn.onclick=()=>renderPhone(btn.dataset.phone));}
  if(page==='messages'){b.innerHTML='<h3>Messages</h3><div class="phone-message"><b>Mom</b><p>left some food in the fridge</p><small>Yesterday · 7:14 PM</small></div><div class="phone-message"><b>Delivery updates</b></div>';const p=document.createElement('p');p.textContent=state.orders.length?state.orders.at(-1).delivered?'Your order was delivered.':'Your order is on its way.':'No new messages.';b.lastChild.append(p);}
  if(page==='discord'){b.innerHTML='<h3>the gc <small>7 members</small></h3><div class="phone-messages"></div><form class="phone-compose"><input placeholder="Message the gc" maxlength="600" aria-label="Phone GC message"><button>↑</button></form>';const list=b.querySelector('.phone-messages');for(const msg of(state.social?.history||[]).slice(-9)){const row=document.createElement('div'),name=document.createElement('b'),txt=document.createElement('p');name.textContent=msg.author||msg.user||msg.name||'the gc';txt.textContent=msg.text;row.append(name,txt);list.append(row);}b.querySelector('form').onsubmit=e=>{e.preventDefault();social.send(b.querySelector('input').value);renderPhone('discord');};}
  if(page==='food'){b.innerHTML=`<h3>Night delivery</h3><p class="muted">Something still open.</p><div class="food-card"><span>↗</span><h4>Corner Kitchen</h4><p>Chicken rice bowl + drink</p><b>$14.50</b><small>25–35 min · delivery included</small><button class="solid-btn" id="order-food">Place order</button></div><p class="muted">Balance: $${state.money.toFixed(2)}</p>`;$('order-food').onclick=()=>{if(state.money<14.5){toast('Not enough in the account.');return;}if(state.orders.some(o=>o.type==='food'&&!o.delivered)){toast('Your order is already on its way.');return;}state.money-=14.5;state.orders.push({id:Date.now(),type:'food',name:'Chicken rice bowl',cost:14.5,arrivesAt:state.totalMinutes+28,delivered:false});save();toast('Order placed. About half an hour.');renderPhone('food');};}
  if(page==='bank'){b.innerHTML=`<h3>Current account</h3><div class="bank-balance"><small>Available balance</small><strong>$${state.money.toFixed(2)}</strong></div><div class="phone-message">Recent activity</div>`;for(const order of state.orders.slice(-6).reverse()){const p=document.createElement('p');p.className='bank-row';p.textContent=`${order.name}  −$${order.cost.toFixed(2)}`;b.append(p);}}
  if(page==='music'){b.innerHTML='<h3>CloudTracks</h3><div class="phone-album">∿</div><h4 id="phone-track"></h4><p id="phone-artist"></p><button class="solid-btn" id="phone-play"></button>';$('phone-track').textContent=state.music?.track?.title||'Nothing playing';$('phone-artist').textContent=state.music?.track?.artist||'Put something on from your PC.';$('phone-play').textContent=state.music?.playing?'Pause':'Play';$('phone-play').onclick=()=>{if(!state.music?.track){toast('Choose a track on the PC first.');return;}state.music.playing=!state.music.playing;if(state.music.playing)audio.playTrack(state.music.track);else audio.pauseMusic();renderPhone('music');};}
  if(page==='camera'){b.innerHTML='<h3>Camera</h3><img class="phone-photo" alt="Your bedroom"><button class="solid-btn" id="take-photo">Take photo</button><p class="muted">Photos stay in this save.</p>';b.querySelector('img').src=room.screenshot();$('take-photo').onclick=()=>{state.photos.push({at:state.totalMinutes,image:room.screenshot()});state.photos=state.photos.slice(-3);save();audio.click();toast('Photo saved.');};}
  if(page==='notes'){b.innerHTML='<h3>Notes</h3><textarea class="notes-input" maxlength="3000" aria-label="Notes"></textarea>';b.querySelector('textarea').value=state.notes;b.querySelector('textarea').oninput=e=>state.notes=e.target.value;}
  if(page==='needs'){b.innerHTML='<h3>Still here.</h3><p class="muted">No rush.</p>';for(const[k,v]of Object.entries(state.needs)){const row=document.createElement('div');row.className='need-row';const label=document.createElement('label');label.textContent=k;const meter=document.createElement('meter');meter.min=0;meter.max=100;meter.value=v;row.append(label,meter);b.append(row);}const temp=document.createElement('p');temp.className='muted';temp.textContent=`PC · ${Math.round(state.temperature)}°C`;b.append(temp);}
}
function togglePhone(force){if(mode!=='room'&&mode!=='bed')return;input.reset();phoneOpen=typeof force==='boolean'?force:!phoneOpen;$('phone').hidden=!phoneOpen;if(phoneOpen){document.exitPointerLock?.();audio.click();renderPhone();}else save();touchControls?.update();}

try{room=createRoom($('world'),ctx);social=createSocial(ctx);ctx.social=social;desktop=createDesktop($('desktop'),ctx);desktop.setSocial?.(social);operator=createOperator($('operator'),ctx);touchControls=createTouchControls(input,state,()=>{const match=mode==='operator'?operator.getState():{};return {mode,blocked:paused||phoneOpen||!$('modal').hidden,chat:match.chatOpen,alive:match.alive,stage:match.stage,scoreboard:match.scoreboardOpen};},touchAction);}catch(error){console.error(error);modal('Unable to start the room.',`<p>This game needs a browser with WebGL enabled. Try Chrome or Edge with hardware acceleration turned on.</p><p class="muted" id="startup-error"></p>`);$('startup-error').textContent=error.message;throw error;}
function touchAction(action){audio.init();if(action==='audio')return;if(action==='pause'){pause();return;}if(action==='phone'){togglePhone();return;}if(action==='desktop'){openApp('discord');return;}if(paused||phoneOpen||!$('modal').hidden)return;if(mode==='room'){if(action==='interact')room.interact();if(action==='pick')room.pick();if(action==='use')room.use();}else if(mode==='operator')operator.mobileAction?.(action);}
$('continue').disabled=!state.savedAt;$('continue').onclick=()=>begin();$('new-game').onclick=()=>{if(!state.savedAt){begin();return;}modal('Start another night?',`<p>Your current night will be replaced. You can export it first.</p><div class="pause-actions"><button class="solid-btn" id="new-confirm">Start new game</button><button id="new-export">Export current save</button><button id="new-cancel">Keep this night</button></div>`);$('new-confirm').onclick=()=>begin(true);$('new-export').onclick=exportSave;$('new-cancel').onclick=closeModal;};
$('menu-settings').onclick=settings;$('credits').onclick=()=>{modal('The people on the other end.',`<p class="credits-intro">ANTICHATLOGGER SIMULATOR</p><p>A small, playable night about Steven, his room, and the GC.</p><p class="muted">Original concept and characters supplied by the player.<br>Built with Three.js and the Web Audio API.<br>All music is original procedural audio. Voice uses your browser’s speech synthesis.<br>Operator opponents, friends, stores, sites, and calls are simulated locally.</p><p>AntiChatLogger · Liltism · Bitsproxy · fxoc · Fear · ShowMeYourPeter · Velcorr</p><button class="solid-btn" id="credits-close">Back to the room</button>`);$('credits-close').onclick=closeModal;};$('quit').onclick=()=>{save();modal('See you around.',`<p>Your night is saved. You can close this tab.</p><button class="solid-btn" id="quit-back">Stay a little longer</button>`);$('quit-back').onclick=closeModal;};
$('capture-mouse').onclick=()=>{audio.init();room.lock();};$('rise').onclick=()=>setMode('room');$('bed-phone').onclick=()=>togglePhone();$('sleep').onclick=()=>{const day=Math.floor(state.totalMinutes/1440);state.totalMinutes=(state.totalMinutes%1440<8*60?day:day+1)*1440+8*60+15;state.needs.energy=96;state.needs.hunger=Math.max(10,state.needs.hunger-15);save();setMode('room');};
document.addEventListener('pointerlockchange',()=>{$('capture-mouse').hidden=!!document.pointerLockElement||mode!=='room'||phoneOpen;});
document.addEventListener('keydown',e=>{
  const typing=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if(typing&&e.code!=='Escape'&&e.code!=='F2'&&!(e.altKey&&e.code==='KeyQ'))return;
  if(e.code==='Escape'){if(phoneOpen){togglePhone(false);return;}if(mode==='operator'){if(!document.pointerLockElement)openApp('discord');return;}if(mode==='menu'){closeModal();return;}pause();return;}
  if(paused)return;
  if(e.code==='F2'||e.altKey&&e.code==='KeyQ'){e.preventDefault();if(mode==='operator')return;if(mode==='pc'&&operator.isRunning()){setMode('operator');operator.show();}return;}
  if(e.code==='Tab'&&(mode==='room'||mode==='bed')){e.preventDefault();togglePhone();return;}if(phoneOpen)return;
  if(e.code==='KeyE'){if(mode==='room')room.interact();else if(mode==='bed')setMode('room');}
  if(e.code==='KeyF'&&mode==='room')room.pick();
});
let subtitleTimer;events.addEventListener('voice',e=>{if(!state.settings.subtitles)return;const el=$('subtitle');el.textContent=`${e.detail.name}: ${e.detail.text}`;el.hidden=false;clearTimeout(subtitleTimer);subtitleTimer=setTimeout(()=>el.hidden=true,6000);});
let lastNotification=-100;events.addEventListener('social-message',e=>{if((mode==='room'||mode==='bed')&&elapsed-lastNotification>40){lastNotification=elapsed;toast(`Discord · ${social.getUnread()} new messages in the gc`);}});
events.addEventListener('settings-change',()=>{room.resize();operator.resize();});
window.addEventListener('beforeunload',()=>{if(state.savedAt)save();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.savedAt)save();});
let last=performance.now();function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.1);last=now;elapsed+=dt;touchControls.update();
  if(!paused&&mode!=='menu'){const delivered=advance(state,dt,mode==='bed',operator.isRunning());for(const order of delivered){toast(order.type==='food'?'Your food is outside the bedroom door.':`${order.name} arrived and is installed.`);audio.notify();save();}social.update(dt);operator.update(dt);desktop.update(dt);
    if(state.totalMinutes>state.events.nextAt){state.events.nextAt=state.totalMinutes+120+Math.random()*210;state.events.eventIndex++;if(state.events.eventIndex%4===0){state.events.outage=true;toast('Connection interrupted. The router is on the dresser.');}else if(state.events.eventIndex%3===0){state.room.rain=!state.room.rain;}save();}
    if(state.totalMinutes%1440>342&&state.totalMinutes%1440<450&&elapsed-lastBird>23){audio.bird();lastBird=elapsed;state.room.rain=false;}
    if(elapsed-lastSave>25){save();lastSave=elapsed;}
  }
  if(mode!=='operator'&&mode!=='pc')room.update(dt);audio.update();$('menu-clock').textContent=ctx.formatTime();$('capture-mouse').hidden=!!document.pointerLockElement||mode!=='room'||phoneOpen||paused;
}requestAnimationFrame(loop);
if(sessionStorage.getItem('anti-start-new')){sessionStorage.removeItem('anti-start-new');begin();}
// Read-only runtime diagnostics for bug reports; no production gameplay cheats.
window.antiDiagnostics=()=>({mode,paused,time:ctx.formatTime(),unread:social.getUnread(),operator:operator.getState?.(),version:state.version});
