import './social.css';

const FRIENDS = {
  AntiChatLogger: { initial: 'a', color: '#9385bc', status: 'online', activity: 'Taking it easy', bio: 'anti\nprobably on operator', since: 'Mar 16, 2018', music: 'underground / reposts', pronouns: 'he/him' },
  Liltism: { initial: 'L', color: '#889c8b', status: 'online', activity: 'Playing APEX CIRCUIT', bio: 'wheel finally works\n1998 / 240sx', since: 'Jul 8, 2019', music: 'rap / garage', pronouns: 'he/him' },
  Bitsproxy: { initial: 'b', color: '#c493b5', status: 'online', activity: 'Playing Roblox', bio: '🇲🇽 • he/him • gay\nfox stuff / web stuff\nbitsproxy.com\nsome days are quieter than others.', since: 'Jan 28, 2017', music: 'ambient / game soundtracks', pronouns: 'he/him' },
  fxoc: { initial: 'fx', color: '#ad927e', status: 'online', activity: 'Listening to dead signal', bio: 'turn it up\nif i dont reply i forgot', since: 'Nov 9, 2019', music: 'rock / shoegaze', pronouns: 'he/him' },
  Fear: { initial: 'F', color: '#a897cf', status: 'dnd', activity: 'Coding on a tablet', bio: 'building something\n8% battery', since: 'Feb 2, 2020', music: 'rap / whatever is playing', pronouns: 'he/him' },
  ShowMeYourPeter: { initial: 'p', color: '#90a4be', status: 'idle', activity: 'Reading', bio: 'There is probably a longer explanation.\nhe/him • gay\nCurrently reading three books very slowly.', since: 'Oct 19, 2018', music: 'jazz / long albums', pronouns: 'he/him' },
  Velcorr: { initial: 'v', color: '#8d959a', status: 'offline', activity: 'Offline', bio: 'around sometimes\nlocal models / image stuff', since: 'May 24, 2019', music: 'electronic', pronouns: 'he/him' },
};
const NAMES = Object.keys(FRIENDS).slice(1);
const SCENES = [
  [['Fear','BITS'],['Fear','HELP'],['Bitsproxy','what'],['Fear','the preview keeps refreshing'],['fxoc','ajdjdjd again'],['Fear','I HAD IT WORKING'],['Bitsproxy','save it before changing tabs'],['Fear','oh'],['Liltism','anyone seen my replay'],['fxoc','you hit a parked car']],
  [['AntiChatLogger','listen to this'],['AntiChatLogger','glass parking — exit light','music'],['fxoc','jsjdhdhd this ass'],['AntiChatLogger','ur ears broken'],['Liltism','bass good'],['fxoc','its literally clipping'],['AntiChatLogger','ye'],['ShowMeYourPeter','I think that is intentional. The distortion sits over everything, but the drums are actually fairly restrained. It would probably sound different with headphones.'],['AntiChatLogger','bro']],
  [['Liltism','wheel arrived'],['AntiChatLogger','finally'],['Liltism','clamp doesnt fit the desk'],['fxoc','GSHDHDH'],['Liltism','sorted it'],['Bitsproxy','nice'],['Liltism','gonna drive for a bit'],['AntiChatLogger','operator later'],['Liltism','ye']],
  [['Fear','BRO'],['Fear','MY CODE WORKED'],['fxoc','JSHDHDHDH no way'],['Fear','IM SERIOUS'],['Fear','preview.png','code'],['Bitsproxy','you fixed the state'],['Fear','THE ASSISTANT DID'],['ShowMeYourPeter','You still had to work out what to ask it. You should save a copy of this version before you change anything else.'],['Fear','WAIT'],['Fear','IT FROZE']],
  [['Velcorr','yo'],['AntiChatLogger','holy shit'],['Velcorr','what'],['AntiChatLogger','ur alive'],['Velcorr','yea'],['AntiChatLogger','where tf u been'],['Velcorr','doing stuff'],['Fear','new model?'],['Velcorr','downloading it']],
  [['Bitsproxy','site is up again'],['Fear','SEND'],['Bitsproxy','bitsproxy.com'],['Fear','clean'],['Bitsproxy','asset browser still broken'],['ShowMeYourPeter','The spacing on the cards is much better. I assume the broken thumbnails are the older uploads?'],['Bitsproxy','yea'],['Bitsproxy','[ASSET REMOVED BY MODERATION]'],['Fear','okay']],
  [['fxoc','this ones actually good'],['fxoc','dead signal — narrow room','music'],['AntiChatLogger','hell nah'],['fxoc','JSHDHDHDH 😭'],['Liltism','i like this one'],['AntiChatLogger','of course u do'],['Bitsproxy','i still have the old one playing'],['Fear','what old one'],['Bitsproxy','from tuesday']],
  [['ShowMeYourPeter','hear me out'],['ShowMeYourPeter','[ATTACHMENT CENSORED]','censored'],['AntiChatLogger','WHAT 😭'],['fxoc','JSHDHDHDHDH????'],['Bitsproxy','why'],['AntiChatLogger','DO NOT TYPE A PARAGRAPH'],['ShowMeYourPeter',"I'm explaining"],['Liltism','operator'],['AntiChatLogger','get on']],
  [['AntiChatLogger','what u doing'],['Bitsproxy','roblox'],['AntiChatLogger','still?'],['Bitsproxy','yea'],['Fear','bits check dm'],['Bitsproxy','one sec'],['fxoc','how long is one sec'],['Bitsproxy','one sec'],['Liltism','valid']],
  [['Fear','storage full'],['Fear','AGAIN'],['Bitsproxy','delete the duplicate exports'],['Fear','i need those'],['Bitsproxy','all 19?'],['Fear','maybe'],['ShowMeYourPeter','You could keep the latest two locally and archive the rest. Naming them something other than final would also help you figure out which is which.'],['fxoc','final final 2 real'],['Fear','thats actually the name']],
  [['Liltism','rain sounds mad on the window'],['AntiChatLogger','ye same here'],['fxoc','mine stopped'],['Bitsproxy','not raining here'],['Liltism','still on'],['AntiChatLogger','ye'],['Liltism','operator update done'],['AntiChatLogger','one min'],['Liltism','aight']],
  [['ShowMeYourPeter','I tried the old version again. It is slower, but there is something about the layout that makes more sense to me. Every time they move the settings I spend ten minutes looking for the same three options.'],['fxoc','what app'],['ShowMeYourPeter','The one from earlier.'],['AntiChatLogger','that was yesterday'],['ShowMeYourPeter','Right, yes.'],['Bitsproxy','i kept the old version'],['Fear','mine updates on its own'],['Bitsproxy','unlucky'],['fxoc','jsjdjd']],
  [['AntiChatLogger','yo'],['Liltism','u see this'],['Liltism','replay still.png','racing'],['fxoc','there is no road there'],['Liltism','there was'],['AntiChatLogger','bro 😭'],['Liltism','steering feels weird'],['Bitsproxy','check the deadzone'],['Liltism','it was me actually']],
  [['Velcorr','new model dropped'],['Fear','WHICH'],['Velcorr','small local one'],['AntiChatLogger','good?'],['Velcorr','idk'],['Velcorr','downloading it'],['ShowMeYourPeter','Let me know if it runs without eating all your memory. I have been meaning to try one on the spare computer.'],['Velcorr','ye'],['Bitsproxy','send later']],
  [['fxoc','she sent me this'],['fxoc','dead signal — left outside','music'],['AntiChatLogger','how tf do u keep pulling'],['fxoc','idk'],['AntiChatLogger','bro'],['Liltism','song decent'],['Fear','THE PAGE LOADED'],['Bitsproxy','nice'],['Fear','only took four minutes']],
  [['Fear','[message deleted]','deleted'],['Bitsproxy','saw it'],['Fear','no you didnt'],['fxoc','JSHDHDHDH'],['Liltism','anyway'],['Liltism','ive driven the same lap for 40 minutes'],['AntiChatLogger','get on operator'],['Liltism','last lap'],['AntiChatLogger','u said that an hour ago']],
];

const LIVE_SCENES = [
  [['Fear','BITS'],['Fear','the button works now'],['Bitsproxy','nice'],['Fear','but only if i dont press it twice'],['fxoc','JSHDHDHDH'],['Bitsproxy','disable it while its loading']],
  [['Liltism','anti'],['Liltism','operator in a bit'],['fxoc','you said that earlier'],['Liltism','im driving'],['Bitsproxy','fear send the new preview']],
  [['fxoc','anyone got music'],['Liltism','speakers already on'],['fxoc','ye we can hear'],['Liltism','its not even loud']],
  [['Fear','BRO'],['Fear','saved it'],['Bitsproxy','good'],['Fear','the tablet just restarted'],['Bitsproxy','good timing']],
  [['ShowMeYourPeter','I went back and listened to the track Anti posted. The second half makes a lot more sense once the first synth drops out. I still think it could lose about forty seconds, but I get it now.'],['fxoc','three days later'],['ShowMeYourPeter','I had the tab open.']],
  [['Bitsproxy','new build up'],['Bitsproxy','roblox studio finally stopped hanging'],['Fear','can i see'],['Bitsproxy','ye check site']],
  [['Liltism','nah this guy'],['Liltism','braked in the middle of the straight'],['fxoc','was it a parked car again'],['Liltism','no']],
  [['Fear','wait'],['Fear','nvm'],['fxoc','ajdjdjd'],['Bitsproxy','what'],['Fear','nothing fixed it']],
  [['fxoc','yo'],['Bitsproxy','yo'],['fxoc','forgot what i was gonna say']],
  [['Liltism','glass parking — exit light','music'],['Liltism','this the one anti posted?'],['fxoc','yeah'],['Liltism','hard']],
  [['Bitsproxy','brb'],['Fear','ok'],['Bitsproxy','back'],['fxoc','that was like 12 seconds'],['Bitsproxy','water']],
  [['ShowMeYourPeter','I am going to leave the call on but I will be away for a while. There is a thing I need to finish reading before I lose the page again.'],['fxoc','ok'],['Liltism','aight']],
  [['Fear','it made a second button'],['Bitsproxy','remove the duplicate'],['Fear','WHICH ONE'],['Bitsproxy','the second one']],
  [['Liltism','last race'],['fxoc','sure'],['Liltism','actually this time']],
];
const SERVER_DATA = {
  music: { title: 'afterimage', initial: 'a.', channels: ['general','new-finds','reposts','production'], messages: [['softblur','anyone have the old version of exit light'],['nacre','think it got deleted'],['shiver404','new one is up on cloudtracks'],['softblur','found it ty'],['roomtone','glow tape vol. 2 tonight']] },
  operator: { title: 'OPERATOR / COMMUNITY', initial: 'OP', channels: ['general','looking-for-game','office','patch-notes'], messages: [['silt','office still the best map'],['latepacket','anyone queue east'],['voidstep','2 spots casual'],['silt','server room hold is so annoying'],['system','Minor stability patch installed.']] },
  dev: { title: 'small projects', initial: '{}', channels: ['general','show-and-tell','help','old-builds'], messages: [['brickwater','finally exported the new build'],['mintcore','looks good'],['Bitsproxy','fixed the thumbnails'],['brickwater','nice'],['system','No new announcements.']] },
};

function node(tag, cls, value) { const e = document.createElement(tag); if(cls) e.className=cls; if(value !== undefined) e.textContent=value; return e; }
function button(cls,text,fn,title) { const b=node('button',cls,text); b.type='button'; if(title)b.title=title; if(fn)b.addEventListener('click',fn); return b; }
function prettyTime(minutes) { const m=((Math.floor(minutes)%1440)+1440)%1440; const hour=Math.floor(m/60); return `${hour%12||12}:${String(m%60).padStart(2,'0')} ${hour>=12?'PM':'AM'}`; }
function dateLabel(minutes) { const day=Math.floor(minutes/1440); if(day===0)return 'September 20, 2026'; const d=new Date(Date.UTC(2026,8,20+day)); return d.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}); }
function seedHistory(now) { const result=[]; let id=1; SCENES.forEach((scene,i)=>{const base=now-1440*(7-Math.floor(i/3))-(i%3)*88; scene.forEach(([author,text,type],j)=>result.push({id:id++,author,text,type:type||'text',time:base+j*(j%4===0?9:1.2)}));}); result.sort((a,b)=>a.time-b.time); const recent=[['Liltism','anyone on'],['fxoc','ye'],['Fear','wait i need to save this'],['Bitsproxy','roblox'],['Liltism','anti operator later'],['ShowMeYourPeter','I am around. Probably just going to sit in the call for a while.'],['fxoc','same'],['Fear','BITS'],['Fear','check dm'],['Bitsproxy','one sec'],['Liltism','last race then im on']];recent.forEach(([author,text],j)=>result.push({id:id++,author,text,type:'text',time:now-18+j*1.4}));return result; }

export function createSocial(ctx) {
  const {state}=ctx;
  if(!state.social)state.social={};
  const s=state.social;
  const defaults={history:seedHistory(state.totalMinutes||1278),dms:{},elapsed:0,nextBurst:54,scene:0,queue:[],unread:0,inCall:false,muted:false,deafened:false,speaker:false,callVolume:70,relationships:{},velcorrVisit:0,nextVoice:27};
  Object.entries(defaults).forEach(([key,value])=>{if(s[key]===undefined)s[key]=value;});
  NAMES.forEach(name=>{if(!s.relationships[name])s.relationships[name]={messages:0,note:''};if(!s.dms[name])s.dms[name]=[{id:`dm-${name}`,author:name,time:(state.totalMinutes||1278)-(name==='Velcorr'?1870:43),text:({Liltism:'operator later?',Bitsproxy:'site works again btw',fxoc:'u heard the new dead signal',Fear:'LOOK I GOT IT RUNNING',ShowMeYourPeter:'I found the link you asked for. It was in the older conversation, about a week further back than I expected.',Velcorr:'this model runs locally'})[name],type:'text'}];});
  let host,root,thread='gc',visible=true,messagesEl,typingEl,headerTitle,headerMeta,callEl,memberEl,dmListEl,composerEl,profileEl,sideTitle,loadCount=65,typing=null,uiTimer=0,voiceLine=null,voiceUntil=0,away=false,lastPresence='';
  let nextId=Math.max(1,...s.history.map(m=>Number(m.id)||0))+1;
  const save=()=>ctx.save?.();
  const operatorParty=()=>Boolean(ctx.isOperatorRunning?.()&&ctx.isOperatorParty?.());
  const presence=name=>{if(name==='AntiChatLogger'||name==='Liltism'&&operatorParty())return 'online';const h=((state.totalMinutes||1278)%1440)/60; if(name==='Velcorr')return s.velcorrVisit>s.elapsed?'online':'offline';if(name==='Bitsproxy')return 'online';if(name==='Liltism')return h>4.3&&h<14?'offline':(away?'idle':'online');if(name==='Fear')return h>4.9&&h<11?'offline':'dnd';if(name==='fxoc')return h>5.5&&h<13?'idle':'online';return h>3.8&&h<12?'offline':'idle';};
  const activity=name=>presence(name)==='offline'?'Offline':name==='AntiChatLogger'&&ctx.isOperatorRunning?.()||name==='Liltism'&&operatorParty()?'Playing OPERATOR':name==='Velcorr'?'Trying a local model':FRIENDS[name]?.activity||'Online';
  function avatar(name,size='') { const data=FRIENDS[name]||{initial:name.slice(0,2),color:'#78817d'};const a=node('div',`s-avatar ${size} ${name==='Bitsproxy'?'s-fox':''}`,data.initial);a.style.setProperty('--avatar',data.color);a.append(node('i',`s-presence s-${presence(name)}`));return a; }
  function mount(container) {
    host=container;host.replaceChildren();root=node('div','s-app');host.append(root);
    const rail=node('nav','s-rail');rail.setAttribute('aria-label','Discord navigation');rail.append(button('s-home s-rail-btn s-active','◒',()=>selectThread('gc'),'Direct messages'));rail.append(node('div','s-rail-sep'));Object.entries(SERVER_DATA).forEach(([key,data])=>rail.append(button('s-rail-btn',data.initial,()=>selectThread(`server:${key}`),data.title)));rail.append(node('div','s-rail-spacer'));rail.append(button('s-rail-btn s-add','+',()=>ctx.toast?.('Your communities are up to date.'),'Explore communities'));root.append(rail);
    const sidebar=node('aside','s-sidebar');const find=node('input','s-find');find.placeholder='Find a conversation';find.setAttribute('aria-label','Find a conversation');find.addEventListener('input',()=>{const q=find.value.toLowerCase();for(const row of dmListEl.querySelectorAll('[data-name]'))row.hidden=!row.dataset.name.toLowerCase().includes(q);});sidebar.append(find);sidebar.append(button('s-friends-link','♙  Friends',()=>showFriends()));sideTitle=node('div','s-side-label','DIRECT MESSAGES');sideTitle.append(node('span','','+'));sidebar.append(sideTitle);dmListEl=node('div','s-dm-list');sidebar.append(dmListEl);root.append(sidebar);
    const user=node('div','s-user');user.append(avatar('AntiChatLogger','s-small'));const userInfo=node('div','s-user-info');userInfo.append(node('b','','AntiChatLogger'),node('span','','Online'));user.append(userInfo);user.append(button('s-icon','⚙',()=>ctx.openApp?.('settings'),'Settings'));sidebar.append(user);
    const main=node('section','s-main');const header=node('header','s-header');header.append(node('span','s-header-symbol','◉'));const titles=node('div','s-header-titles');headerTitle=node('strong','','the gc');headerMeta=node('span','','7 members');titles.append(headerTitle,headerMeta);header.append(titles);const tools=node('div','s-header-tools');tools.append(button('s-icon','◖',toggleCall,'Join / leave group call'));tools.append(button('s-icon','♙',()=>root.classList.toggle('s-show-members'),'Toggle member list'));tools.append(button('s-icon','⌕',()=>{const box=root.querySelector('.s-search-messages');box.hidden=!box.hidden;if(!box.hidden)box.focus();},'Search messages'));header.append(tools);main.append(header);const search=node('input','s-search-messages');search.placeholder='Search this conversation…';search.hidden=true;search.setAttribute('aria-label','Search messages');search.addEventListener('input',()=>renderMessages(search.value));main.append(search);
    callEl=node('div','s-call-region');main.append(callEl);const body=node('div','s-thread-body');messagesEl=node('div','s-messages');messagesEl.setAttribute('role','log');messagesEl.setAttribute('aria-label','Conversation');messagesEl.addEventListener('scroll',()=>{if(messagesEl.scrollTop<8&&loadCount<getMessages().length){const old=messagesEl.scrollHeight;loadCount+=40;renderMessages('',false);messagesEl.scrollTop=messagesEl.scrollHeight-old;}});body.append(messagesEl);memberEl=node('aside','s-members');body.append(memberEl);main.append(body);typingEl=node('div','s-typing');main.append(typingEl);composerEl=node('div','s-composer');main.append(composerEl);root.append(main);
    profileEl=node('div','s-profile-layer');profileEl.hidden=true;root.append(profileEl);renderSidebar();renderMembers();renderCall();renderComposer();renderMessages();
  }
  function renderSidebar() { if(!dmListEl)return;dmListEl.replaceChildren();const gc=button(`s-dm ${thread==='gc'?'s-selected':''}`,'',()=>selectThread('gc'));gc.dataset.name='the gc';const icon=node('div','s-gc-avatar','◒');gc.append(icon);const label=node('div','s-dm-copy');label.append(node('b','','the gc'),node('span','','7 members'));gc.append(label);if(s.unread)gc.append(node('i','s-unread',String(s.unread)));dmListEl.append(gc);NAMES.forEach(name=>{const row=button(`s-dm ${thread===name?'s-selected':''}`,'',()=>selectThread(name));row.dataset.name=name;row.append(avatar(name,'s-small'));const info=node('div','s-dm-copy');info.append(node('b','',name),node('span','',activity(name)));row.append(info);dmListEl.append(row);}); }
  function renderMembers() { if(!memberEl)return;memberEl.replaceChildren(node('div','s-members-title',`MEMBERS — 7`));Object.keys(FRIENDS).forEach(name=>{const row=button('s-member','',()=>showProfile(name));row.append(avatar(name,'s-small'));const copy=node('div','s-member-copy');copy.append(node('b','',name),node('span','',activity(name)));row.append(copy);if(presence(name)==='offline')row.classList.add('s-offline-member');memberEl.append(row);}); }
  function selectThread(value) { thread=value;loadCount=65;typing=null;if(thread==='gc'&&visible)s.unread=0;const server=thread.startsWith('server:')?SERVER_DATA[thread.split(':')[1]]:null;if(headerTitle){headerTitle.textContent=server?server.title:thread==='gc'?'the gc':thread;headerMeta.textContent=server?'# general':thread==='gc'?'7 members':activity(thread);root.classList.toggle('s-server-view',!!server);}renderSidebar();renderMessages();renderCall();renderComposer();renderTyping();save(); }
  function getMessages() {if(thread==='gc')return s.history;if(thread.startsWith('server:')){const data=SERVER_DATA[thread.split(':')[1]];return data.messages.map(([author,text],i)=>({id:`server-${i}`,author,text,time:state.totalMinutes-60+i*9}));}return s.dms[thread]||[];}
  function renderMessages(filter='',bottom=true) { if(!messagesEl)return;const oldTop=messagesEl.scrollTop;messagesEl.replaceChildren();let list=getMessages();if(filter)list=list.filter(m=>`${m.text} ${m.author}`.toLowerCase().includes(filter.toLowerCase()));const start=Math.max(0,list.length-loadCount);if(start>0)messagesEl.append(button('s-load-old',`↑  Earlier messages · ${start} more`,()=>{loadCount+=60;renderMessages('',false);}));else{const welcome=node('div','s-conversation-start');welcome.append(node('div','s-welcome-icon',thread==='gc'?'◒':'#'),node('h2','',thread==='gc'?'the gc':thread.startsWith('server:')?SERVER_DATA[thread.split(':')[1]].title:thread),node('p','',thread==='gc'?'Same people. Different tabs.':thread.startsWith('server:')?'You are all caught up in #general.':`Your conversation with ${thread}.`));messagesEl.append(welcome);}let day=null;list.slice(start).forEach((m,i)=>{const d=Math.floor(m.time/1440);if(d!==day){const divider=node('div','s-date');divider.append(node('span','',dateLabel(m.time)));messagesEl.append(divider);day=d;}const prev=list[start+i-1];const grouped=prev&&prev.author===m.author&&Math.abs(m.time-prev.time)<3&&m.type!=='music';messagesEl.append(messageNode(m,grouped));});if(!list.length)messagesEl.append(node('div','s-empty','No messages found.'));if(bottom)messagesEl.scrollTop=messagesEl.scrollHeight;else messagesEl.scrollTop=oldTop; }
  function messageNode(m,grouped=false) {const row=node('article',`s-message ${grouped?'s-grouped':''}`);row.dataset.message=m.id;if(!grouped){const av=button('s-avatar-button','',()=>FRIENDS[m.author]&&showProfile(m.author),`View ${m.author}'s profile`);av.append(avatar(m.author));row.append(av);}else row.append(node('span','s-hover-time',prettyTime(m.time).split(' ')[0]));const content=node('div','s-message-content');if(!grouped){const line=node('div','s-message-author');const name=button('s-name',m.author,()=>FRIENDS[m.author]&&showProfile(m.author));name.style.color=FRIENDS[m.author]?.color||'#a9adbf';line.append(name,node('time','',prettyTime(m.time)));content.append(line);}if(m.type==='music'){const music=button('s-music-embed','',()=>ctx.openApp?.('cloudtracks'));music.append(node('div','s-track-art','◒'));const text=node('div','s-track-info');text.append(node('span','s-embed-source','CLOUDTRACKS'),node('b','',m.text),node('span','','◷ 2:34   ·   692 plays'));music.append(text,node('div','s-embed-play','▶'));content.append(music);}else if(m.type==='censored'){content.append(node('div','s-censored','[ATTACHMENT CENSORED]'));}else if(m.type==='code'){const panel=node('div','s-code-snapshot');panel.append(node('div','s-code-title','preview — tablet browser'),node('div','s-code-mock','project is running'),node('span','','build completed • 840 ms'));content.append(panel);}else if(m.type==='racing'){const panel=node('div','s-race-snapshot');panel.append(node('div','s-race-road'),node('span','','REPLAY  00:14.82'),node('b','','APEX CIRCUIT'));content.append(panel);}else content.append(node('p',m.type==='deleted'?'s-deleted':'',m.text));row.append(content);return row; }
  function renderComposer() { if(!composerEl)return;composerEl.replaceChildren();if(thread.startsWith('server:')){const channels=node('div','s-server-channels');SERVER_DATA[thread.split(':')[1]].channels.forEach(ch=>channels.append(button('s-channel',`# ${ch}`,()=>ctx.toast?.(ch==='general'?'You are in #general.':`#${ch} · No recent messages.`))));composerEl.append(channels,node('div','s-server-notice','You usually just read here.'));return;}const form=node('form','s-compose-form');const plus=button('s-compose-plus','+',()=>{const menu=root.querySelector('.s-attach-menu');if(menu){menu.remove();return;}const choices=node('div','s-attach-menu');choices.append(button('','♫ Share a track',()=>{send('glass parking — exit light','music');choices.remove();}),button('','▧ Mystery attachment',()=>{send('[ATTACHMENT CENSORED]','censored');choices.remove();}));composerEl.append(choices);},'Send an attachment');const input=node('input','s-message-input');input.placeholder=`Message ${thread==='gc'?'the gc':'@'+thread}`;input.maxLength=1600;input.setAttribute('aria-label',`Message ${thread==='gc'?'the gc':thread}`);const submit=button('s-send','↵',null,'Send message');submit.type='submit';form.append(plus,input,submit);form.addEventListener('submit',event=>{event.preventDefault();if(input.value.trim()){send(input.value);input.value='';}});composerEl.append(form);const suggested=node('div','s-suggestions');['yo','operator','hop call','listen to this'].forEach(text=>suggested.append(button('s-suggestion',text,()=>{if(text==='listen to this')send('glass parking — exit light','music');else send(text);})));suggested.append(node('span','s-compose-hint','Enter to send'));composerEl.append(suggested); }
  function addMessage(author,text,type='text',target='gc') {const msg={id:nextId++,author,text,type,time:state.totalMinutes||1278};const list=target==='gc'?s.history:(s.dms[target]||(s.dms[target]=[]));list.push(msg);if(list.length>1800)list.splice(0,list.length-1800);if(author!=='AntiChatLogger'){if(!visible||thread!==target){s.unread++;if(s.unread===1){ctx.audio?.notify?.();if(text.toLowerCase().includes('anti'))ctx.toast?.(`${author}: ${text}`);}}ctx.events?.dispatchEvent(new CustomEvent('social-message',{detail:{message:msg,unread:s.unread}}));}if(thread===target&&messagesEl){const nearBottom=messagesEl.scrollHeight-messagesEl.scrollTop-messagesEl.clientHeight<100;renderMessages('',nearBottom||author==='AntiChatLogger');}renderSidebar();save(); }
  function enqueue(author,text,delay=4,type='text',target='gc') {s.queue.push({author,text,type,target,due:s.elapsed+delay});if(author==='ShowMeYourPeter'&&delay>10)typing={name:author,until:s.elapsed+delay,target};}
  function send(text,type='text',target=thread) {text=String(text).trim().slice(0,1600).replace(/\bn[i1]gg(?:er|a)s?\b/gi,'n****').replace(/\bf[a4]gg?(?:ot)?s?\b/gi,'f*****');if(!text||target.startsWith('server:')||target==='friends')return;addMessage('AntiChatLogger',text,type,target);ctx.audio?.click?.();const t=text.toLowerCase();if(target!=='gc'){s.relationships[target].messages++;if(presence(target)==='offline')return;const responses={Liltism:t.includes('operator')?'ye last race':t.includes('mic')?'what about it':'hold on im driving',Bitsproxy:t.includes('doing')?'roblox':t.includes('site')?'bitsproxy.com. still fixing some stuff':t.includes('code')?'send the error':'yea',fxoc:t.includes('music')?'sent one in gc':type==='music'?'jsjdjd nah':'ajdjdjd what',Fear:t.includes('code')?'WAIT LOOK':'BRO I WAS ABOUT TO MESSAGE YOU',ShowMeYourPeter:'I saw this earlier but I was halfway through something and forgot to reply. I am here now, although I might be a little slow because I still have several tabs open.',Velcorr:'ye'};enqueue(target,responses[target],target==='ShowMeYourPeter'?25:target==='Bitsproxy'?11:5,'text',target);return;}if(type==='music'){enqueue('fxoc','jsjdhdhd where do u find these',9);enqueue('Liltism','this hard',22);return;}if(type==='censored'){enqueue('Bitsproxy','why',6);enqueue('fxoc','JSHDHDHDH????',8);return;}if(t.includes('operator')||t==='get on'){enqueue('Liltism','ye give me a minute',7);enqueue('Liltism','last race',13);return;}if(t.includes('call')){enqueue('Liltism','im in here',5);return;}if(t.includes('mic')||t.includes('loud')){enqueue('Liltism','its not even loud',8);s.speaker=false;ctx.audio?.setSpeaker?.(false);return;}if(t.includes('bits')){enqueue('Bitsproxy','what',14);return;}if(t.includes('fear')){enqueue('Fear','WAIT',3);enqueue('Fear','ITS ALMOST DONE',4.8);return;}if(t.includes('velcorr')&&presence('Velcorr')!=='offline'){enqueue('Velcorr','yo',17);return;}if(t.includes('doing')){enqueue('Bitsproxy','roblox',14);enqueue('Liltism','driving',19);return;}if(t==='yo'&&Math.random()>.5){enqueue('fxoc','yo',28);return;}if(Math.random()>.6)enqueue('Liltism','ye',19+Math.random()*30); }
  function toggleCall() {s.inCall=!s.inCall;ctx.audio?.setCall?.(s.inCall&&!s.deafened);if(!s.inCall){s.speaker=false;ctx.audio?.setSpeaker?.(false);}else{s.nextVoice=s.elapsed+12;ctx.toast?.('Connected to the gc');}renderCall();save();}
  function renderCall() {if(!callEl)return;callEl.replaceChildren();if(thread!=='gc')return;if(!s.inCall){const banner=node('div','s-call-banner');const faces=node('div','s-call-faces');faces.append(avatar('Liltism','s-tiny'),avatar('fxoc','s-tiny'));banner.append(faces);const copy=node('div','s-call-banner-text');copy.append(node('b','','The call is still going'),node('span','','Liltism, fxoc and 2 others'));banner.append(copy,button('s-join','Join call',toggleCall));callEl.append(banner);return;}const panel=node('div','s-call-panel');const webcam=node('div',`s-webcam ${away?'s-camera-away':''}`);webcam.setAttribute('aria-label',away?"Liltism's webcam: empty chair, desk and racing wheel":"Liltism's webcam: racing at his wheel");webcam.append(node('div','s-cam-wall'),node('div','s-cam-screen'),node('div','s-cam-speaker'),node('div','s-cam-chair'),node('div','s-cam-person'),node('div','s-cam-head'),node('div','s-cam-arm s-left-arm'),node('div','s-cam-arm s-right-arm'),node('div','s-cam-desk'),node('div','s-cam-wheel'));const cameraName=node('span','s-cam-name','Liltism');cameraName.prepend(node('i','s-live-dot'));webcam.append(cameraName,node('span','s-cam-quality','480p · LIVE'));panel.append(webcam);const participants=node('div','s-call-participants');['Bitsproxy','fxoc','ShowMeYourPeter',...(presence('Velcorr')==='online'?['Velcorr']:[])].forEach(name=>{const tile=button(`s-call-tile ${voiceLine?.name===name&&s.elapsed<voiceUntil?'s-speaking':''}`,'',()=>showProfile(name));tile.append(avatar(name),node('span','',name),node('i','s-tile-mute',name==='Velcorr'||name==='ShowMeYourPeter'?'⌁':''));participants.append(tile);});panel.append(participants);callEl.append(panel);const bottom=node('div','s-call-bottom');const connected=node('span','s-connected','◉ Voice connected');bottom.append(connected);const controls=node('div','s-call-controls');controls.append(button(`s-call-control ${s.muted?'s-toggled':''}`,s.muted?'Mic off':'Mic on',()=>{s.muted=!s.muted;renderCall();save();},'Toggle microphone'),button(`s-call-control ${s.deafened?'s-toggled':''}`,s.deafened?'Deafened':'Headset',()=>{s.deafened=!s.deafened;ctx.audio?.setCall?.(!s.deafened);ctx.audio?.setSpeaker?.(s.speaker&&!s.deafened);renderCall();save();},'Toggle deafen'),button('s-call-control s-disconnect','Disconnect',toggleCall));bottom.append(controls);callEl.append(bottom);const caption=node('div','s-voice-caption');if(voiceLine&&s.elapsed<voiceUntil&&!s.deafened){caption.append(node('b','',`${voiceLine.name} `),node('span','',voiceLine.text));}else caption.textContent=s.deafened?'You are deafened.':' ';callEl.append(caption);}
  function renderTyping() {if(!typingEl)return;typingEl.replaceChildren();if(typing&&typing.until>s.elapsed&&typing.target===thread){typingEl.append(node('span','s-typing-dots','•••'),node('b','',typing.name),document.createTextNode(' is typing…'));}}
  function showProfile(name) {if(!profileEl||!FRIENDS[name])return;const data=FRIENDS[name];profileEl.replaceChildren();profileEl.hidden=false;const shade=button('s-profile-shade','',()=>profileEl.hidden=true,'Close profile');const card=node('section','s-profile-card');const banner=node('div','s-profile-banner');banner.style.background=`linear-gradient(135deg,${data.color}70,#26272f)`;banner.append(button('s-profile-close','×',()=>profileEl.hidden=true,'Close profile'));card.append(banner);const content=node('div','s-profile-content');content.append(avatar(name,'s-profile-avatar'),node('h2','',name),node('div','s-profile-status',`${presence(name)==='dnd'?'Do not disturb':presence(name)} · ${data.pronouns}`));content.append(node('div','s-profile-rule'));content.append(node('h4','','ABOUT ME'),node('p','s-bio',data.bio),node('h4','','CURRENT ACTIVITY'),node('p','',activity(name)),node('h4','','MEMBER SINCE'),node('p','',data.since),node('h4','','LISTENS TO'),node('p','',data.music));if(name!=='AntiChatLogger'){const note=node('textarea','s-profile-note');note.placeholder='Click to add a note';note.value=s.relationships[name].note;note.setAttribute('aria-label',`Private note about ${name}`);note.addEventListener('change',()=>{s.relationships[name].note=note.value;save();});content.append(node('h4','','NOTE'),note);if(s.inCall&&name!=='Velcorr'){const label=node('label','s-volume-label',`User volume · ${s.callVolume}%`);const slider=node('input','s-volume');slider.type='range';slider.min=0;slider.max=100;slider.value=s.callVolume;slider.setAttribute('aria-label','Call volume');slider.addEventListener('input',()=>{s.callVolume=Number(slider.value);label.textContent=`User volume · ${s.callVolume}%`;save();});content.append(label,slider);}if(name==='Velcorr')content.append(node('div','s-profile-footnote','Communicates through text.'));content.append(button('s-profile-message','Message',()=>{profileEl.hidden=true;selectThread(name);}));}card.append(content);profileEl.append(shade,card);}
  function showFriends() {if(!messagesEl)return;thread='friends';headerTitle.textContent='Friends';headerMeta.textContent='All friends';callEl.replaceChildren();composerEl.replaceChildren();messagesEl.replaceChildren(node('h2','s-friends-heading','ALL FRIENDS — 6'));NAMES.forEach(name=>{const row=button('s-friend-row','',()=>showProfile(name));row.append(avatar(name));const info=node('div');info.append(node('b','',name),node('p','',activity(name)));row.append(info,node('span','s-friend-message','Message  ›'));messagesEl.append(row);});renderSidebar();}
  function update(dt) {
    s.elapsed+=Math.min(dt,5);uiTimer+=dt;
    if(s.elapsed>=s.nextBurst){s.nextBurst=s.elapsed+45+Math.random()*65;const nightHour=((state.totalMinutes||1278)%1440)/60;const quiet=(nightHour>4&&nightHour<12)?0.55:0.23;if(Math.random()>quiet){const scene=LIVE_SCENES[s.scene++%LIVE_SCENES.length];let delay=1;scene.forEach(([author,text,type])=>{if(presence(author)!=='offline'){enqueue(author,text,delay,type);delay+=author==='Fear'?1.2:3+Math.random()*6;}});}else{typing={name:'ShowMeYourPeter',until:s.elapsed+7,target:'gc'};}}
    const next=s.queue.filter(q=>q.due>s.elapsed).sort((a,b)=>a.due-b.due)[0];if(next&&next.due-s.elapsed<6&&(!typing||typing.until<s.elapsed)){typing={name:next.author,until:next.due,target:next.target};}
    const ready=s.queue.filter(q=>q.due<=s.elapsed);s.queue=s.queue.filter(q=>q.due>s.elapsed);ready.forEach(q=>{if(q.author!=='Velcorr'||presence('Velcorr')!=='offline')addMessage(q.author,q.text,q.type,q.target);});
    if(!s.velcorrSeen&&s.elapsed>340){s.velcorrSeen=true;s.velcorrVisit=s.elapsed+175;enqueue('Velcorr','yo',5);enqueue('Velcorr','new model is alright',38);save();}
    if(s.inCall&&s.elapsed>=s.nextVoice){s.nextVoice=s.elapsed+40+Math.random()*95;const lines=[['Liltism','hold on'],['fxoc','yo'],['Liltism','IM DRIVING'],['Bitsproxy','one sec'],['ShowMeYourPeter','I think that is the old version.'],['Liltism','this guy just hit me'],['fxoc','nvm'],['Liltism','its not even loud']];if(Math.random()>.35){const [name,text]=lines[Math.floor(Math.random()*lines.length)];if(presence(name)!=='offline'){voiceLine={name,text};voiceUntil=s.elapsed+6;if(!s.deafened&&s.callVolume>0)ctx.audio?.voice?.(name,text);}}if(Math.random()<.15){s.speaker=!s.speaker;ctx.audio?.setSpeaker?.(s.speaker&&!s.deafened);}if(Math.random()<.12)away=!away;renderCall();}
    if(uiTimer>1){uiTimer=0;renderTyping();const current=Object.keys(FRIENDS).map(n=>presence(n)+activity(n)).join();if(current!==lastPresence){lastPresence=current;renderMembers();renderSidebar();if(FRIENDS[thread]&&headerMeta)headerMeta.textContent=activity(thread);if(thread==='friends')showFriends();if(s.inCall)renderCall();}if(voiceLine&&s.elapsed>voiceUntil){voiceLine=null;renderCall();}}
  }
  function setVisible(value) {visible=!!value;if(visible&&thread==='gc'){s.unread=0;renderSidebar();}}
  return {mount,update,send:(text,type='text')=>send(text,type,'gc'),setVisible,getUnread:()=>s.unread,destroy:()=>{host?.replaceChildren();},joinCall:()=>{if(!s.inCall)toggleCall();},friends:FRIENDS};
}
